### ISSUE TITLE
upgrade to latest holochain 0.4x version

### ISSUE THREAD

**Issue by nphias** [holochain-open-dev/holoom#10]
binaries for all architectures will be created for 0.4x version

**Comment by 8e8b2c** [comment]
We're currently pinned to v0.2.6 because that's the version the holo team have been providing support for. That said, I can see from chatter in mattermost that it might be prudent for us to jump to v0.4.x. Holo is testing against v0.4.0-dev.2, so I'm guessing it's still in flux.

Changing versions is somewhat tedious because it involves producing corresponding binaries. (Thankfully handled by https://github.com/holochain-open-dev/holochain-prebuilt-binaries). I'll check with the holo team to see which version they think we should be targeting.

**Comment by 8e8b2c** [comment]
Related: https://github.com/holochain/holochain/issues/2958

**Comment by nphias** [comment]
closing this issue as 0.4x upgrade was done
